import {
  LayoutList, LayoutDashboard, Filter, SlidersHorizontal,
  ChevronDown, ChevronRight, ChevronLeft, ChevronUp,
  X, Plus, Search, MoreHorizontal, MoreVertical,
  CheckCircle2, Circle, PauseCircle, Clock, AlertCircle,
  User, Users, Building2, Cpu, Calendar,
  AlertTriangle, Trash2, ExternalLink, Eye, EyeOff,
  GripVertical, ArrowUpDown, FileText, Menu, Bell,
  Check, Info, RefreshCw, LogOut, Settings,
} from 'lucide-react';

export const ICONS = {
  viewList:    LayoutList,
  viewKanban:  LayoutDashboard,
  filter:      Filter,
  settings:    SlidersHorizontal,
  search:      Search,
  close:       X,
  add:         Plus,
  more:        MoreHorizontal,
  moreV:       MoreVertical,
  drag:        GripVertical,
  sort:        ArrowUpDown,
  show:        Eye,
  hide:        EyeOff,
  external:    ExternalLink,
  delete:      Trash2,
  chevronDown:  ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft:  ChevronLeft,
  chevronUp:    ChevronUp,
  check:        Check,
  refresh:      RefreshCw,
  menu:         Menu,
  bell:         Bell,
  logout:       LogOut,
  config:       Settings,
  statusDisponivel:   Circle,
  statusEmAndamento:  Clock,
  statusEmPausa:      PauseCircle,
  statusVencida:      AlertCircle,
  statusConcluida:    CheckCircle2,
  task:        FileText,
  scat:        LayoutDashboard,
  user:        User,
  users:       Users,
  sector:      Building2,
  system:      Cpu,
  client:      Building2,
  calendar:    Calendar,
  warning:     AlertTriangle,
  info:        Info,
} as const;

export type IconKey = keyof typeof ICONS;
