export const STRINGS = {
  actions: {
    save:       'Salvar',
    cancel:     'Cancelar',
    close:      'Fechar',
    back:       'Voltar',
    apply:      'Aplicar',
    clear:      'Limpar filtros',
    retry:      'Tentar novamente',
    loading:    'Carregando...',
    viewDetail: 'Ver detalhe',
    openScat:   'Abrir SCAT',
  },
  nav: {
    inicio:  'Início',
    tarefas: 'Tarefas',
    scats:   'SCATs',
    sistema: 'EVP — Gestão',
  },
  tarefas: {
    titulo:  'Tarefas',
    views: {
      lista:   'Lista',
      kanban:  'Kanban',
    },
    toolbar: {
      busca:   'Buscar por descrição...',
      filtros: 'Filtros',
      colunas: 'Colunas',
    },
    colunas: {
      id:          '#',
      scat:        'SCAT',
      descricao:   'Descrição',
      status:      'Status',
      responsavel: 'Responsável',
      setor:       'Setor',
      cliente:     'Cliente',
      sistema:     'Sistema',
      tipo:        'Tipo',
      inicio:      'Início',
      termino:     'Previsão',
      terminadoEm: 'Concluído em',
      horas:       'Horas',
      pontos:      'Pontos',
      acoes:       '',
    },
    lista: {
      empty:        'Nenhuma tarefa encontrada',
      emptyFiltros: 'Nenhuma tarefa encontrada com os filtros aplicados',
    },
    kanban: {
      statusAtualizado: (status: string) => `Status atualizado para "${status}"`,
      erroAtualizar:    'Erro ao atualizar status da tarefa',
    },
    filtros: {
      titulo:            'Filtros de Tarefas',
      setor:             'Setor',
      setoresInativos:   'Exibir setores inativos',
      numeroSolicitacao: 'Número da Solicitação',
      tipoErro:          'Tipo de Erro',
      sistema:           'Sistema',
      cliente:           'Cliente',
      tipoSolicitacao:   'Tipo de Solicitação',
      previsaoTermino:   'Previsão de Término',
      inicio:            'Início',
      fim:               'Fim',
      de:                'De',
      ate:               'Até',
      status:            'Status',
      excluidas:         'Exibir excluídas',
      origem:            'Origem',
      origemInterna:     'Interna',
      origemExterna:     'Externa',
      origemTodas:       'Todas',
      tipoTarefa:        'Tipo de Tarefa',
      tipoFinalizacao:   'Tipo de Finalização',
      comErro:           'Com Erro',
      comErroTodas:      'Todas',
      comErroSo:         'Só com erro',
      comErroSem:        'Só sem erro',
      filtrosAtivos:     (n: number) => `${n} filtro${n !== 1 ? 's' : ''} ativo${n !== 1 ? 's' : ''}`,
    },
    detalhe: {
      titulo:          'Detalhe da Tarefa',
      infoGeral:       'Informações Gerais',
      datas:           'Datas e Horas',
      adicional:       'Informações Adicionais',
      scat:            'SCAT',
      responsavel:     'Responsável',
      setor:           'Setor',
      cliente:         'Cliente',
      sistema:         'Sistema',
      tipoTarefa:      'Tipo de Tarefa',
      inicio:          'Início',
      previsao:        'Previsão de Término',
      terminadoEm:     'Concluído em',
      horas:           'Horas Trabalhadas',
      pontos:          'Pontos Previstos',
      origem:          'Origem',
      tipoFinalizacao: 'Tipo de Finalização',
      expectativa:     'Expectativa do Fornecedor',
      comErro:         'Com Erro',
      sim:             'Sim',
      nao:             'Não',
      semValor:        '—',
      interna:         'Interna',
      externa:         'Externa',
      abrirScat:       'Abrir SCAT',
    },
  },
  scats: {
    titulo:  'SCATs',
    toolbar: {
      busca: 'Buscar por título ou número...',
    },
    colunas: {
      numero:      'Nº SCAT',
      titulo:      'Título',
      status:      'Status',
      prioridade:  'Prioridade',
      cliente:     'Cliente',
      sistema:     'Sistema',
      responsavel: 'Responsável',
      abertura:    'Abertura',
      previsao:    'Previsão',
      progresso:   'Progresso',
    },
    empty:  'Nenhuma SCAT encontrada',
    detalhe: {
      titulo:          'Detalhe da SCAT',
      descricao:       'Descrição',
      cliente:         'Cliente',
      sistema:         'Sistema',
      setor:           'Setor',
      responsavel:     'Responsável',
      solicitante:     'Solicitante',
      tipoSolicitacao: 'Tipo de Solicitação',
      prioridade:      'Prioridade',
      abertura:        'Data de Abertura',
      previsao:        'Previsão',
      conclusao:       'Conclusão',
      tarefas:         'Tarefas',
      semTarefas:      'Esta SCAT não possui tarefas cadastradas.',
      semValor:        '—',
      progresso:       'Progresso',
    },
  },
  errors: {
    generic:      'Algo deu errado. Tente novamente.',
    notFound:     'Não encontrado.',
    taskNotFound: 'Tarefa não encontrada.',
    scatNotFound: 'SCAT não encontrada.',
    network:      'Sem conexão. Verifique sua internet.',
  },
} as const;
